name: Unzip file

on:
  push:
    branches:
      - master

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2

    - name: Unzip file
      run: unzip yourfile.zip -d output_directory

    - name: Commit unzipped content
      run: |
        git config --global user.email "your-email@example.com"
        git config --global user.name "yourusername"
        git add output_directory/
        git commit -m "Add unzipped content"
        git push
